sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
branches:
  only:
    - master
